name: 'Slack-Lazy'
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - actions-slack

jobs:
  slack-lazy:
    name: 'Slack Lazy'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Show $GTIHUB environment
        id: github
        run: |
          echo $GITHUB | jq -r .
        env:
          GITHUB: ${{ toJSON(github) }}

      - name: Test
        id: test
        run: |
          echo "TEST"

      - name: Slack Notification Drift
        uses: lazy-actions/slatify@master
        with:
          type: ${{ job.status }}
          username: isysitm-infra-drift
          job_name: '*Test*'
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
